### PR TITLE
rechunk array by zyx

### PR DESCRIPTION
**Pull request by pr4deepr**
rechunk array by zyx; 
Not sure about "A" dimension

### CODE REVIEW

**Comment by pr4deepr** [comment]
You should consider renaming this to something like "reader".

**Comment by sebi06** [comment]
Hi @pr4deepr 

When one ready a 2d image plane using pylibCZIrw one get:

- an array with shape (Y, X, 1) for gray-scale pixel types
- an array with shape (Y, X, 3) for bgr pixel types

Inside the CZI specification this "pixel type dimension is defined as the "A" dimension --> it returns an array with dimensions YXA.

But when really working with those data in the grayscale-case it is very convenient to just remove this A dimension to just have an array with shape YX

**Comment by pr4deepr** [comment]
Thanks for the info about "A" dimension..

My understanding is that Its usually a good idea to have chunksize similar to size of the underlying data. As images will usually be accessed in ZYX if its 3D, I rechunked it to that. 

However, you are right the performance is better with without rechunking in napari.
I was testing a 16 GB dataset CZYX (3, 185, 4160, 3719) and napari loaded quickly and was more responsive than if I used rechunking. I tested the compute time and it was almost the same as well. 
I'll remove it from the code..

**Comment by sebi06** [comment]
Hi @pr4deepr ,

I added your suggestion incl renaming and various other changes directly. I added an option to rechunk ZYX - otherwise it will use the initial chunking. There I will close this PR. Feel free to test the work_in_progress branch and open a new PR.

Thx for your input. It is really appreciated :-)

**Pull request closed without merging**
